export const stationslocations = [
    {
        "id": "MA_10043753",
        "type": 0,
        "brand": "shell",
        "name": "MANSOUR (AGADIR)",
        "lat": 30.408352,
        "lng": -9.588639,
        "country_code": "MA",
        "address": "Angle Boulevard Hassan II Med V",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 1.40999989074,
        "driving_distance": 1.586,
        "driving_duration": 258,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043753-mansour-agadir/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Angle Boulevard Hassan II Med V\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043831",
        "type": 2,
        "brand": "shell",
        "name": "LUCIEN SAINT",
        "lat": 30.425055,
        "lng": -9.605908,
        "country_code": "MA",
        "address": "Angle Rue Chouhada et Avenue Hassan II",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 1.08817334056,
        "driving_distance": 1.638,
        "driving_duration": 233,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043831-lucien-saint/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Angle Rue Chouhada et Avenue Hassan II\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043675",
        "type": 2,
        "brand": "shell",
        "name": "ANZA",
        "lat": 30.435019,
        "lng": -9.641614,
        "country_code": "MA",
        "address": "Route Anza",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "bottled_gas",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 4.52283896407,
        "driving_distance": 5.689,
        "driving_duration": 577,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043675-anza/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Anza\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043678",
        "type": 0,
        "brand": "shell",
        "name": "ARGANIERS",
        "lat": 30.363252,
        "lng": -9.536414,
        "country_code": "MA",
        "address": "Km 9 Inzegane-Agadir",
        "city": "Inzegane",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 8.49804954548,
        "driving_distance": 9.281,
        "driving_duration": 985,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043678-arganiers/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Km 9 Inzegane-Agadir\nInzegane",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043815",
        "type": 2,
        "brand": "shell",
        "name": "KSIMA",
        "lat": 30.362804,
        "lng": -9.534991,
        "country_code": "MA",
        "address": "Km 10 Rte Ait Melloul Inzeggan Agadir",
        "city": "Inzegan",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 8.630195414080001,
        "driving_distance": 9.426,
        "driving_duration": 1001,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043815-ksima/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Km 10 Rte Ait Melloul Inzeggan Agadir\nInzegan",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043895",
        "type": 2,
        "brand": "shell",
        "name": "ROCADE AGADIR",
        "lat": 30.391411,
        "lng": -9.516626,
        "country_code": "MA",
        "address": "Route Express Agadir Vers Tikiouine",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "bottled_gas",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "tyre_service",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 8.42417551153,
        "driving_distance": 11.492,
        "driving_duration": 1102,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043895-rocade-agadir/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Express Agadir Vers Tikiouine\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043800",
        "type": 2,
        "brand": "shell",
        "name": "JIHADIA",
        "lat": 30.360411,
        "lng": -9.526638,
        "country_code": "MA",
        "address": "Route Ait Melloul Inzeggane Agadir",
        "city": "Inzegan",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 9.396029008080001,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043800-jihadia/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Ait Melloul Inzeggane Agadir\nInzegan",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043952",
        "type": 2,
        "brand": "shell",
        "name": "TIKIOUINE",
        "lat": 30.378225,
        "lng": -9.504303,
        "country_code": "MA",
        "address": "Route De Marrakech Tikiouine Agadir",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "tyre_service",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 10.081656611980002,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043952-tikiouine/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route De Marrakech Tikiouine Agadir\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043690",
        "type": 2,
        "brand": "shell",
        "name": "BAICH AIT MELLOUL",
        "lat": 30.311021,
        "lng": -9.502932,
        "country_code": "MA",
        "address": "Route Tiznit-Ait Melloul",
        "city": "Ait Melloul",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "tyre_service",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 14.98691277567,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043690-baich-ait-melloul/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Tiznit-Ait Melloul\nAit Melloul",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10087464",
        "type": 2,
        "brand": "shell",
        "name": "AIT MELLOUL ID HALI",
        "lat": 30.323003,
        "lng": -9.486429,
        "country_code": "MA",
        "address": "Route de Ait Melloul",
        "city": "Inzegan",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 15.05651144144,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10087464-ait-melloul-id-hali/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route de Ait Melloul\nInzegan",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043750",
        "type": 0,
        "brand": "shell",
        "name": "EL KLEA",
        "lat": 30.30275,
        "lng": -9.466009,
        "country_code": "MA",
        "address": "Route Tafroute Kolea Centre",
        "city": "Ait Melloul",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "air_and_water",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 18.03305612584,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043750-el-klea/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Tafroute Kolea Centre\nAit Melloul",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043672",
        "type": 2,
        "brand": "shell",
        "name": "AMSKROUDE",
        "lat": 30.531533,
        "lng": -9.330139,
        "country_code": "MA",
        "address": "Route De Marrakech, Amskroud",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "twenty_four_hour",
            "restaurant",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 28.75674443487,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043672-amskroude/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route De Marrakech, Amskroud\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043712",
        "type": 2,
        "brand": "shell",
        "name": "BIOUGRA",
        "lat": 30.223475,
        "lng": -9.380693,
        "country_code": "MA",
        "address": "Route Tafilalt Biougra",
        "city": "Chtouka Ait Baha",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 30.06291178857,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043712-biougra/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Tafilalt Biougra\nChtouka Ait Baha",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_1100022",
        "type": 2,
        "brand": "shell",
        "name": "BIOUGRA AMAGAR",
        "lat": 30.209733,
        "lng": -9.380712,
        "country_code": "MA",
        "address": "Route Ait Amira",
        "city": "Biougra",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "restaurant",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 31.1754201893,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_1100022-biougra-amagar/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Ait Amira\nBiougra",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043867",
        "type": 2,
        "brand": "shell",
        "name": "O.TAIMA GL",
        "lat": 30.39165,
        "lng": -9.217025,
        "country_code": "MA",
        "address": "O Taima Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 36.76582328412,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043867-o-taima-gl/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "O Taima Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043786",
        "type": 2,
        "brand": "shell",
        "name": "HAD BELFAA",
        "lat": 30.045158,
        "lng": -9.566842,
        "country_code": "MA",
        "address": "Route NÂ°1 Vers Tiznit",
        "city": "Agadir",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "restaurant",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "tyre_service",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 41.47847658417,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043786-had-belfaa/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route NÂ°1 Vers Tiznit\nAgadir",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043950",
        "type": 0,
        "brand": "shell",
        "name": "TIDZI (OULAD SAID)",
        "lat": 30.3115996,
        "lng": -9.1672763,
        "country_code": "MA",
        "address": "Sidi Said Centre O, Taime",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 43.07369983404,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043950-tidzi-oulad-said/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Sidi Said Centre O, Taime\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043694",
        "type": 0,
        "brand": "shell",
        "name": "BELFAA ROUTE PPLE",
        "lat": 30.0155757,
        "lng": -9.5810594,
        "country_code": "MA",
        "address": "Hay Belfaa Route Tiznit",
        "city": "Chtouka Ait Baha",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "food_offerings",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "tyre_service"
        ],
        "inactive": false,
        "distance": 44.6850599448,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043694-belfaa-route-pple/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Hay Belfaa Route Tiznit\nChtouka Ait Baha",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043795",
        "type": 2,
        "brand": "shell",
        "name": "IM MKORN",
        "lat": 30.16302,
        "lng": -9.23508,
        "country_code": "MA",
        "address": "Immkorne Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "hgv_lane",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 44.95543809416,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043795-im-mkorn/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Immkorne Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043837",
        "type": 0,
        "brand": "shell",
        "name": "MASSA",
        "lat": 29.978492,
        "lng": -9.626224,
        "country_code": "MA",
        "address": "Massa Centre Province Agadir",
        "city": "Chtouka Ait Baha",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "air_and_water",
            "bottled_gas",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 48.84322921122,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043837-massa/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Massa Centre Province Agadir\nChtouka Ait Baha",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043667",
        "type": 0,
        "brand": "shell",
        "name": "AIT MILK",
        "lat": 29.9506043,
        "lng": -9.3871151,
        "country_code": "MA",
        "address": "Ait Milk",
        "city": "Ait Milk",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 55.73874071994,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043667-ait-milk/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Ait Milk\nAit Milk",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043945",
        "type": 2,
        "brand": "shell",
        "name": "TAROUDANTE (SAADA)",
        "lat": 30.456793,
        "lng": -8.874772,
        "country_code": "MA",
        "address": "Route Taroudante",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 69.59616055316,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043945-taroudante-saada/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Taroudante\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043866",
        "type": 2,
        "brand": "shell",
        "name": "O.TAIMA AP",
        "lat": 30.4760948,
        "lng": -8.864928,
        "country_code": "MA",
        "address": "Route Taroudante 0 Tayma Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 70.69774468817,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043866-o-taima-ap/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Taroudante 0 Tayma Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043944",
        "type": 2,
        "brand": "shell",
        "name": "TAROUDANTE (BOULAADAM)",
        "lat": 30.476112,
        "lng": -8.864827,
        "country_code": "MA",
        "address": "Route Nationale Taroudante-Ouarzazat vers Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "bottled_gas",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 70.7075561092,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043944-taroudante-boulaadam/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Nationale Taroudante-Ouarzazat vers Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_1100012",
        "type": 2,
        "brand": "shell",
        "name": "AZOUL",
        "lat": 29.702149,
        "lng": -9.717957,
        "country_code": "MA",
        "address": "Azoul Tiznit Naftam",
        "city": "Tiznit",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 80.31898233413001,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_1100012-azoul/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Azoul Tiznit Naftam\nTiznit",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043711",
        "type": 0,
        "brand": "shell",
        "name": "BICHA TIZNITE (YOUSSOUFIA)",
        "lat": 29.693002,
        "lng": -9.72856,
        "country_code": "MA",
        "address": "Avenue Hassan Ii Quartier El Youssoufia",
        "city": "Tiznit",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 81.4755651299,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043711-bicha-tiznite-youssoufia/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Avenue Hassan Ii Quartier El Youssoufia\nTiznit",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043899",
        "type": 2,
        "brand": "shell",
        "name": "SAADAOUI (TIZNIT AVENIR)",
        "lat": 29.687354,
        "lng": -9.724284,
        "country_code": "MA",
        "address": "Tiznit Centre",
        "city": "Tiznit",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "bottled_gas",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 82.03495410465,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043899-saadaoui-tiznit-avenir/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Tiznit Centre\nTiznit",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043680",
        "type": 0,
        "brand": "shell",
        "name": "ASMAA",
        "lat": 30.999753,
        "lng": -9.036369,
        "country_code": "MA",
        "address": "Route Agadir Vers Marrakech, Agrave",
        "city": "Chichaoua",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "air_and_water",
            "twenty_four_hour",
            "shop",
            "selectshop",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 84.21914235345001,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043680-asmaa/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Agadir Vers Marrakech, Agrave\nChichaoua",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043666",
        "type": 0,
        "brand": "shell",
        "name": "AIT IGGAS",
        "lat": 30.546127,
        "lng": -8.712858,
        "country_code": "MA",
        "address": "Ait Iggas Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "air_and_water",
            "twenty_four_hour",
            "manned"
        ],
        "inactive": false,
        "distance": 86.14265257372,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043666-ait-iggas/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Ait Iggas Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043924",
        "type": 2,
        "brand": "shell",
        "name": "SMIMOU",
        "lat": 31.211601,
        "lng": -9.70505,
        "country_code": "MA",
        "address": "Route D'agadir",
        "city": "Smimou",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "hgv_lane",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 88.91715296587999,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043924-smimou/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route D'agadir\nSmimou",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043865",
        "type": 2,
        "brand": "shell",
        "name": "O BERHIL",
        "lat": 30.62578,
        "lng": -8.49297,
        "country_code": "MA",
        "address": "Oute Ourzazate, O, Berhil",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "credit_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 108.47766785872,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043865-o-berhil/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Oute Ourzazate, O, Berhil\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043796",
        "type": 2,
        "brand": "shell",
        "name": "IMINE TANOUTE",
        "lat": 31.17923,
        "lng": -8.85571,
        "country_code": "MA",
        "address": "Quartier Izourane Bd 25 Imintanoute",
        "city": "Chichaoua",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "bottled_gas",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 110.56496610813,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043796-imine-tanoute/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Quartier Izourane Bd 25 Imintanoute\nChichaoua",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043794",
        "type": 0,
        "brand": "shell",
        "name": "IGHERM",
        "lat": 30.087555,
        "lng": -8.461178,
        "country_code": "MA",
        "address": "Ighram Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "air_and_water",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 115.29270390633,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043794-igherm/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Ighram Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043676",
        "type": 2,
        "brand": "shell",
        "name": "AOULOUZ",
        "lat": 30.670993,
        "lng": -8.17858,
        "country_code": "MA",
        "address": "Aoulouz Centre Route Agadir-Ouarzazate",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "restaurant",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 138.94765421642,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043676-aoulouz/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Aoulouz Centre Route Agadir-Ouarzazate\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043787",
        "type": 0,
        "brand": "shell",
        "name": "HAD MEJJAT",
        "lat": 31.3545,
        "lng": -8.5110665,
        "country_code": "MA",
        "address": "Had Mejjat",
        "city": "Chichaoua",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "air_and_water",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 147.12790713373002,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043787-had-mejjat/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Had Mejjat\nChichaoua",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043731",
        "type": 2,
        "brand": "shell",
        "name": "CHICHAOUA",
        "lat": 31.532758,
        "lng": -8.766649,
        "country_code": "MA",
        "address": "Route d'Agadir-Chichaoua",
        "city": "Chichaoua",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "bottled_gas",
            "credit_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 147.27343774338,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043731-chichaoua/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route d'Agadir-Chichaoua\nChichaoua",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043936",
        "type": 2,
        "brand": "shell",
        "name": "TALIOUINE S. H'SAINE",
        "lat": 30.5312657,
        "lng": -7.9238785,
        "country_code": "MA",
        "address": "Route Taroudante, Route Sidi Hsaine, Taliouine",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "hgv_lane",
            "air_and_water",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 161.05739422382,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043936-taliouine-s-h-saine/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Taroudante, Route Sidi Hsaine, Taliouine\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043937",
        "type": 0,
        "brand": "shell",
        "name": "TALOUINE",
        "lat": 30.531677,
        "lng": -7.922409,
        "country_code": "MA",
        "address": "Route Ouarzazate-Taliouine vers Centre",
        "city": "Taroudant",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "air_and_water",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 161.20104976688,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043937-talouine/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Ouarzazate-Taliouine vers Centre\nTaroudant",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043782",
        "type": 2,
        "brand": "shell",
        "name": "GUELMIM",
        "lat": 28.978756,
        "lng": -10.076529,
        "country_code": "MA",
        "address": "Route De Tan Tan Km 4 - Goulimine",
        "city": "Guelmim",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 166.45071311693002,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043782-guelmim/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route De Tan Tan Km 4 - Goulimine\nGuelmim",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043830",
        "type": 2,
        "brand": "shell",
        "name": "LOUDAYA",
        "lat": 31.634516,
        "lng": -8.247465,
        "country_code": "MA",
        "address": "Loudaya",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "bottled_gas",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 186.85336077735,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043830-loudaya/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Loudaya\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043805",
        "type": 2,
        "brand": "shell",
        "name": "JRIFATES",
        "lat": 32.1062572,
        "lng": -9.0819914,
        "country_code": "MA",
        "address": "Route Sebt Gzoula Jerifate",
        "city": "Safi",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 194.14999164331,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043805-jrifates/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Sebt Gzoula Jerifate\nSafi",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_1100050",
        "type": 0,
        "brand": "shell",
        "name": "Abdama Marrakech (RED TRADING)",
        "lat": 31.6292794,
        "lng": -8.0952126,
        "country_code": "MA",
        "address": "Complexe Commercial Â« El KawkabÂ», Gueliz",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "service_bay",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 196.73703963633,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_1100050-abdama-marrakech-red-trading/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Complexe Commercial Â« El KawkabÂ», Gueliz\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043789",
        "type": 0,
        "brand": "shell",
        "name": "HAOUZ",
        "lat": 31.637233,
        "lng": -8.017498,
        "country_code": "MA",
        "address": "Angle Bd Med V Et Bd Abdelkrim El Khattabi Quartier Azli N?",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "atm",
            "standard_toilet",
            "carwash",
            "service_bay",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "wifi",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "selectshop",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 202.78067366381998,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043789-haouz/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Angle Bd Med V Et Bd Abdelkrim El Khattabi Quartier Azli N?\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_1100034",
        "type": 0,
        "brand": "shell",
        "name": "TARGA",
        "lat": 31.67908,
        "lng": -8.060119,
        "country_code": "MA",
        "address": "Avenue Yacoub El Mansour, Route de Targa, Marrakech 40000",
        "city": "Targa",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 202.94609271413,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_1100034-targa/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Avenue Yacoub El Mansour, Route de Targa, Marrakech 40000\nTarga",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043682",
        "type": 0,
        "brand": "shell",
        "name": "ATLAS MARRAKECH",
        "lat": 31.644042,
        "lng": -8.019067,
        "country_code": "MA",
        "address": "Angle Bd Abdelkerim Khatabi Amp",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "selectshop",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 203.17316230326998,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043682-atlas-marrakech/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Angle Bd Abdelkerim Khatabi Amp\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043881",
        "type": 2,
        "brand": "shell",
        "name": "PALMERAIE",
        "lat": 31.649911,
        "lng": -8.020229,
        "country_code": "MA",
        "address": "Bd Abdelkrim Khattabi",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 203.52662812939002,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043881-palmeraie/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Bd Abdelkrim Khattabi\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043824",
        "type": 0,
        "brand": "shell",
        "name": "LES AMIS",
        "lat": 31.623592,
        "lng": -7.990306,
        "country_code": "MA",
        "address": "Angle Bd My Ismail And Rue Al Mowahidine",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 203.71987431355998,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043824-les-amis/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Angle Bd My Ismail And Rue Al Mowahidine\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10068020",
        "type": 2,
        "brand": "shell",
        "name": "MASSAR",
        "lat": 31.66855,
        "lng": -8.037164,
        "country_code": "MA",
        "address": "Route De Safi Quartier Massar",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "food_offerings",
            "air_and_water",
            "loyalty_cards",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "shop",
            "selectshop",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 203.73598279837998,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10068020-massar/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route De Safi Quartier Massar\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_gasoline",
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043968",
        "type": 0,
        "brand": "shell",
        "name": "ZAHIA",
        "lat": 31.639517,
        "lng": -8.004382,
        "country_code": "MA",
        "address": "Angle Yakoub El Mansour and Bir Anzarane",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "air_and_water",
            "credit_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "oil_and_lubricants"
        ],
        "inactive": false,
        "distance": 203.87903640864002,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043968-zahia/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Angle Yakoub El Mansour and Bir Anzarane\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    },
    {
        "id": "MA_10043743",
        "type": 2,
        "brand": "shell",
        "name": "DOUM",
        "lat": 31.65622,
        "lng": -8.021668,
        "country_code": "MA",
        "address": "Route Safi-Marrakesh",
        "city": "Marrakech",
        "state": "",
        "postcode": "",
        "telephone": "+212 5229-20020",
        "country": "Morocco",
        "amenities": [
            "standard_toilet",
            "carwash",
            "service_bay",
            "hgv_lane",
            "air_and_water",
            "loyalty_cards",
            "bottled_gas",
            "credit_card",
            "fuel_card",
            "shell_card",
            "twenty_four_hour",
            "manned",
            "prayer_room",
            "oil_and_lubricants",
            "hgv_lane"
        ],
        "inactive": false,
        "distance": 203.89498199576,
        "driving_distance": null,
        "driving_duration": null,
        "website_url": "https://find.shell.com/ma/fuel/MA_10043743-doum/fr_MA",
        "mdm_site_category": "Other",
        "formatted_address": "Route Safi-Marrakesh\nMarrakech",
        "site_category": "conventional_fuel_site",
        "open_status": "twenty_four_hour",
        "next_open_status_change": null,
        "tz_offset": 0,
        "fuels": [
            "premium_diesel",
            "fuelsave_midgrade_gasoline",
            "fuelsave_regular_diesel"
        ],
        "next_forecourt_open_status_change": null,
        "next_shop_open_status_change": null,
        "forecourt_open_status": "twenty_four_hour",
        "shop_open_status": "unknown"
    }
]